[[redirects]]
  from = "https://taimoorsattar.dev/*"
  to = "https://taimoorsattar.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/books/workflow-to-build-static-website"
  to = "/p/build-standout-website"
	status = 200

[[redirects]]
  from = "/books/how-to-build-JAMstack-site"
  to = "/p/build-standout-website"
	status = 200
  
[[redirects]]
  from = "/blogs/monolithic-and-microservice-architecture-for-website-development"
  to = "/blogs/what-is-jamstack"
	status = 200

[[redirects]]
  from = "/my-work"
  to = "https://www.notion.so/taimoorsattar/Taimoor-Sattar-d5567816c47f4c91b875b76bdad3fcc8"
	status = 200

[[plugins]]
package = "@netlify/plugin-gatsby"

[[plugins]]
package = "@netlify/plugin-local-install-core"